// Copyright 2026 Schuberg Philis
// SPDX-License-Identifier: Apache-2.0
//! Hand-rolled tokenizer for the spike SQL subset.
//!
//! Lemon only generates the parser; the lexer is always the grammar author's
//! problem. Tokens are `(TokenType, Tok)` pairs, where `TokenType` is the enum
//! *generated by lemon* from the terminals used in `src/parse.y`.

use crate::parser::{ParseError, TokenType};

/// The semantic value carried by every terminal: the token text (borrowed from
/// the input) plus its byte offset, for error messages.
#[derive(Debug, Clone, Copy)]
pub struct Tok<'i> {
    pub text: &'i str,
    pub pos: u32,
}

/// Two-lifetime alias for [`Tok`].
///
/// Why: `%token_type {...}` in a Lemon grammar is a *C code block*, and Lemon's
/// block scanner treats `'` as the start of a character literal. A block
/// containing `Tok<'i>` (an odd number of quotes) makes the scanner run off and
/// swallow the rest of the grammar. Writing `Tok2<'i, 'i>` keeps the quote count
/// even, so the scanner terminates at the right brace. The generated
/// `enum YYMINORTYPE<'i>` also *requires* the token type to actually use `'i`
/// (E0392), so a lifetime-free token type is not an option either.
pub type Tok2<'a, 'b> = Tok<'a>;

/// Tokenize `sql`. Returns an error for lexical problems (e.g. an unterminated
/// string literal) rather than panicking.
pub fn tokenize(sql: &str) -> Result<Vec<(TokenType, Tok<'_>)>, ParseError> {
    let b = sql.as_bytes();
    let mut out = Vec::new();
    let mut i = 0usize;

    while i < b.len() {
        let c = b[i];
        if c.is_ascii_whitespace() {
            i += 1;
            continue;
        }
        let start = i;

        let ty = match c {
            b'(' => { i += 1; TokenType::LP }
            b')' => { i += 1; TokenType::RP }
            b',' => { i += 1; TokenType::COMMA }
            b'.' if !(i + 1 < b.len() && b[i + 1].is_ascii_digit()) => { i += 1; TokenType::DOT }
            b'+' => { i += 1; TokenType::PLUS }
            b'-' => { i += 1; TokenType::MINUS }
            b'*' => { i += 1; TokenType::STAR }
            b'/' => { i += 1; TokenType::SLASH }
            b'%' => { i += 1; TokenType::REM }
            b'=' => { i += 1; TokenType::EQ }
            b'<' => match b.get(i + 1) {
                Some(b'=') => { i += 2; TokenType::LE }
                Some(b'>') => { i += 2; TokenType::NE }
                _ => { i += 1; TokenType::LT }
            },
            b'>' => match b.get(i + 1) {
                Some(b'=') => { i += 2; TokenType::GE }
                _ => { i += 1; TokenType::GT }
            },
            b'!' => match b.get(i + 1) {
                Some(b'=') => { i += 2; TokenType::NE }
                _ => return Err(ParseError::new(format!("unexpected character \"!\" at offset {start}"))),
            },
            b'|' => match b.get(i + 1) {
                Some(b'|') => { i += 2; TokenType::CONCAT }
                _ => return Err(ParseError::new(format!("unexpected character \"|\" at offset {start}"))),
            },
            b'\'' => {
                i += 1;
                loop {
                    match b.get(i) {
                        None => {
                            return Err(ParseError::new(format!(
                                "unterminated string literal starting at offset {start}"
                            )))
                        }
                        Some(b'\'') if b.get(i + 1) == Some(&b'\'') => i += 2,
                        Some(b'\'') => {
                            i += 1;
                            break;
                        }
                        Some(_) => i += 1,
                    }
                }
                TokenType::STRING
            }
            b'"' => {
                // Quoted identifier.
                i += 1;
                loop {
                    match b.get(i) {
                        None => {
                            return Err(ParseError::new(format!(
                                "unterminated quoted identifier starting at offset {start}"
                            )))
                        }
                        Some(b'"') => {
                            i += 1;
                            break;
                        }
                        Some(_) => i += 1,
                    }
                }
                TokenType::ID
            }
            b'0'..=b'9' | b'.' => {
                let mut is_float = false;
                while i < b.len() && b[i].is_ascii_digit() {
                    i += 1;
                }
                if b.get(i) == Some(&b'.') {
                    is_float = true;
                    i += 1;
                    while i < b.len() && b[i].is_ascii_digit() {
                        i += 1;
                    }
                }
                if matches!(b.get(i), Some(b'e') | Some(b'E')) {
                    is_float = true;
                    i += 1;
                    if matches!(b.get(i), Some(b'+') | Some(b'-')) {
                        i += 1;
                    }
                    while i < b.len() && b[i].is_ascii_digit() {
                        i += 1;
                    }
                }
                if is_float {
                    TokenType::FLOAT
                } else {
                    TokenType::INTEGER
                }
            }
            _ if is_ident_start(c) => {
                while i < b.len() && is_ident_part(b[i]) {
                    i += 1;
                }
                keyword(&sql[start..i])
            }
            _ => {
                return Err(ParseError::new(format!(
                    "unexpected character \"{}\" at offset {start}",
                    c as char
                )))
            }
        };

        out.push((
            ty,
            Tok {
                text: &sql[start..i],
                pos: start as u32,
            },
        ));
    }
    Ok(out)
}

fn is_ident_start(c: u8) -> bool {
    c.is_ascii_alphabetic() || c == b'_' || c >= 0x80
}

fn is_ident_part(c: u8) -> bool {
    is_ident_start(c) || c.is_ascii_digit()
}

/// Map an identifier onto its keyword token, or `ID` if it is not a keyword.
fn keyword(word: &str) -> TokenType {
    // Only the keywords the subset needs; everything else stays an identifier,
    // which is why `count(...)` and a column called `name` both work.
    let mut buf = [0u8; 16];
    let bytes = word.as_bytes();
    if bytes.len() > buf.len() {
        return TokenType::ID;
    }
    for (dst, src) in buf.iter_mut().zip(bytes) {
        *dst = src.to_ascii_uppercase();
    }
    match &buf[..bytes.len()] {
        b"ALL" => TokenType::ALL,
        b"AND" => TokenType::AND,
        b"AS" => TokenType::AS,
        b"ASC" => TokenType::ASC,
        b"BY" => TokenType::BY,
        b"CREATE" => TokenType::CREATE,
        b"DELETE" => TokenType::DELETE,
        b"DESC" => TokenType::DESC,
        b"DISTINCT" => TokenType::DISTINCT,
        b"EXISTS" => TokenType::EXISTS,
        b"FROM" => TokenType::FROM,
        b"GROUP" => TokenType::GROUP,
        b"HAVING" => TokenType::HAVING,
        b"IF" => TokenType::IF,
        b"INSERT" => TokenType::INSERT,
        b"INTO" => TokenType::INTO,
        b"KEY" => TokenType::KEY,
        b"LIMIT" => TokenType::LIMIT,
        b"NOT" => TokenType::NOT,
        b"NULL" => TokenType::NULL,
        b"OFFSET" => TokenType::OFFSET,
        b"OR" => TokenType::OR,
        b"ORDER" => TokenType::ORDER,
        b"PRIMARY" => TokenType::PRIMARY,
        b"SELECT" => TokenType::SELECT,
        b"SET" => TokenType::SET,
        b"TABLE" => TokenType::TABLE,
        b"UPDATE" => TokenType::UPDATE,
        b"VALUES" => TokenType::VALUES,
        b"WHERE" => TokenType::WHERE,
        _ => TokenType::ID,
    }
}
