// Copyright 2026 Schuberg Philis
// SPDX-License-Identifier: Apache-2.0
//! Validates that every `mcdc__<id>__vN_<description>` tagged test
//! (#52, #368) still names a real obligation — the failure mode this
//! guards against is silent: a code edit shifts a decision's line
//! number, the obligation id (`<file>_<line>`) changes, and the old
//! tagged tests keep passing (they're ordinary `#[test]` fns exercising
//! real behavior) while quietly no longer counting toward MC/DC
//! discharge, because `cargo-mvl-mcdc harvest` joins tagged tests to
//! obligations by id and finds no match. `make test-mcdc`'s dashboard
//! would eventually show this as an obligation stuck at 0/N vectors,
//! but nothing forces anyone to run it or read it.
//!
//! Deliberately NOT a re-run of `cargo-mvl-mcdc scan`: that requires an
//! external tool most `cargo test` runs (including CI) don't have
//! installed, so this reads the committed snapshot
//! (`tests/mcdc/obligations.json`, regenerated by `make mcdc-obligations`
//! whenever a code change shifts a decision's line) instead — same
//! "committed evidence, regenerable on demand" split as the corpus
//! fixtures (spec 004).

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::arithmetic_side_effects
)]

use std::collections::HashSet;
use std::fs;

/// Mirrors the Makefile's `MCDC_FILES` glob expansion — keep in sync
/// (there is no programmatic way to share a Makefile variable with a
/// Rust test; `src/btree/*.rs`, `src/btree/table/*.rs`, and
/// `src/btree/index/*.rs` are spelled out explicitly here).
const MCDC_FILES: &[&str] = &[
    "src/btree.rs",
    "src/btree/error.rs",
    "src/btree/index.rs",
    "src/btree/master.rs",
    "src/btree/schema.rs",
    "src/btree/table.rs",
    "src/btree/table/delete.rs",
    "src/btree/table/insert.rs",
    "src/btree/index/delete.rs",
    "src/btree/index/insert.rs",
    "src/vdbe/functions.rs",
    "src/parser/grammar.rs",
    "src/parser/tokenizer.rs",
    "src/vdbe/exec.rs",
    "src/record/encode.rs",
    "src/vdbe/program.rs",
    "src/vdbe/control.rs",
];

fn manifest_path(rel: &str) -> String {
    format!("{}/{rel}", env!("CARGO_MANIFEST_DIR"))
}

/// Every id present in the committed obligations snapshot, real or
/// compiler-void — a tagged test naming any of these ids is at least
/// pointing at something that still exists in the source (compiler-void
/// ids just shouldn't be tagged, since they need no vectors).
///
/// Hand-rolled `"id": "..."` extraction rather than a JSON crate: this
/// repo has zero runtime dependencies and minimal dev-dependencies by
/// design, and `cargo-mvl-mcdc scan`'s output is a flat, machine-written
/// array where every object's `id` field is a simple quoted string with
/// no escapes — a full parser would buy nothing here.
fn known_obligation_ids() -> HashSet<String> {
    let raw = fs::read_to_string(manifest_path("tests/mcdc/obligations.json"))
        .expect("tests/mcdc/obligations.json must exist — run `make mcdc-obligations`");
    raw.match_indices("\"id\":")
        .filter_map(|(idx, _)| {
            let rest = raw[idx + "\"id\":".len()..].trim_start();
            let rest = rest.strip_prefix('"')?;
            let end = rest.find('"')?;
            Some(rest[..end].to_string())
        })
        .collect()
}

/// `mcdc__<id>__v<N>_<description>` — `id` is greedy-safe here because
/// it's always followed by the literal `__v` marker before the vector
/// number, so `_` inside `id` itself (e.g. `grammar_2270`) doesn't
/// confuse the split.
fn tagged_obligation_ids(source: &str) -> Vec<String> {
    let mut ids = Vec::new();
    for (idx, _) in source.match_indices("fn mcdc__") {
        let rest = &source[idx + "fn mcdc__".len()..];
        let Some(marker) = rest.find("__v") else {
            continue;
        };
        let candidate = &rest[..marker];
        // Confirm `__v` is actually followed by digits (the vector
        // number), not coincidental text inside a longer id.
        let after = &rest[marker + "__v".len()..];
        if after.chars().next().is_some_and(|c| c.is_ascii_digit()) {
            ids.push(candidate.to_string());
        }
    }
    ids
}

#[test]
fn every_tagged_mcdc_test_names_a_real_obligation() {
    let known = known_obligation_ids();
    let mut stale = Vec::new();

    for file in MCDC_FILES {
        let path = manifest_path(file);
        let Ok(source) = fs::read_to_string(&path) else {
            continue;
        };
        for id in tagged_obligation_ids(&source) {
            if !known.contains(&id) {
                stale.push(format!("{file}: mcdc__{id}__..."));
            }
        }
    }

    assert!(
        stale.is_empty(),
        "these tagged MC/DC tests name obligation ids that no longer exist in \
         tests/mcdc/obligations.json — the decision they were tagged against has \
         moved to a different line (rename the tests to the current id) or been \
         removed entirely (delete the stale tests). Regenerate the snapshot first \
         with `make mcdc-obligations` if source has changed since it was last \
         committed, then re-run this test:\n{}",
        stale.join("\n")
    );
}
