// Copyright 2026 Schuberg Philis
// SPDX-License-Identifier: Apache-2.0
//! Committed-fixture tests for the pager (spec 007 / 001-architecture
//! Req-4): hot-journal recovery, WAL-pending reads, auto-vacuum and
//! single-page fixtures under `tests/corpus/fixtures/journalstates/`,
//! generated by the pinned oracle via `tools/gen_fixtures.sh`.
//!
//! These lived in `db-storage/src/row/pager/mod.rs`'s `tests::fixtures` module until the pager
//! moved to `db_storage::row::pager` (t-rust-db/sqlite-rs#3); the fixtures
//! stayed here, so the tests now drive the re-exported public API as a
//! black-box integration test (db-storage carries no copy of the fixtures —
//! t-rust-db/db-storage#11).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic
)]

use std::path::Path;

use sqlite_rs::btree::TableCursor;
use sqlite_rs::header::DatabaseHeader;
use sqlite_rs::pager::Pager;
use sqlite_rs::record::{decode_record, TextEncoding, Value};
use sqlite_rs::schema::read_schema;
use sqlite_rs::vfs::{UnixVfs, Vfs};

fn header_of(vfs: &UnixVfs, path: &Path) -> DatabaseHeader {
    let file = vfs.open_read(path).unwrap();
    let mut buf = [0u8; 100];
    file.read_at(&mut buf, 0).unwrap();
    DatabaseHeader::parse(&buf).unwrap()
}

fn text(v: &Value) -> &str {
    match v {
        Value::Text(s) => s,
        other => panic!("expected text, got {other:?}"),
    }
}

/// 001-architecture Req-4's "Hot journal is never ignored" scenario,
/// upgraded by #172 from refuse-and-explain to actual recovery: the
/// fixture's main file already has ~1999 uncommitted, spilled rows
/// written into it (see tools/gen_fixtures.sh) and a *real*
/// `sqlite3`-written journal recording their pre-images. `Pager::open`
/// must replay that journal — proving interop with a stock `sqlite3`
/// journal, not just our own — leaving only the one row genuinely
/// committed before the transaction started.
///
/// Copies the fixture pair into a scratch temp dir first: recovery
/// mutates the main file and deletes the journal in place, and the
/// checked-in fixture under `tests/corpus/fixtures/` must stay
/// byte-identical for every other test that reads it.
#[test]
fn hot_journal_fixture_recovers_committed_state() {
    let dir = std::env::temp_dir().join(format!(
        "sqlite-rs-hot-journal-recovery-test-{}",
        std::process::id()
    ));
    std::fs::create_dir_all(&dir).unwrap();
    let db_path = dir.join("hot_journal.db");
    std::fs::copy(
        "tests/corpus/fixtures/journalstates/hot_journal.db",
        &db_path,
    )
    .unwrap();
    std::fs::copy(
        "tests/corpus/fixtures/journalstates/hot_journal.db-journal",
        dir.join("hot_journal.db-journal"),
    )
    .unwrap();

    let rows = read_table_t_at(&db_path);

    assert_eq!(rows, vec![(1, "committed-before".to_string())]);
    assert!(!dir.join("hot_journal.db-journal").exists());

    std::fs::remove_dir_all(&dir).unwrap();
}

/// "Zero behavior change on at-rest fixtures": the same assertions
/// `db-storage/src/row/btree/mod.rs`'s `single_page_table_first_row` makes against
/// `VfsPageSource` must hold identically through `Pager`.
#[test]
fn table_single_page_fixture_reads_identically_through_pager() {
    let vfs = UnixVfs;
    let path = Path::new("tests/corpus/fixtures/btrees/table_single_page.db");
    let header = header_of(&vfs, path);
    let pager = Pager::open(&vfs, path, header.page_size).unwrap();
    let mut cursor = TableCursor::new(pager, &header, 1);

    let row = cursor.first_row().unwrap().unwrap();
    let values = decode_record(&row.payload, TextEncoding::Utf8).unwrap();
    assert_eq!(text(&values[0]), "table");
    assert_eq!(text(&values[1]), "t");
    assert_eq!(text(&values[4]), "CREATE TABLE t(a INTEGER, b TEXT)");
}

/// Freelist/pointer-map awareness: the auto-vacuum fixture's
/// pointer-map page (page 2) sits between sqlite_master (page 1)
/// and table `t`'s actual root — root page is discovered via
/// `read_schema`, never hardcoded, so this proves the b-tree
/// cursor's pointer-following traversal is unaffected by the
/// interleaved pointer-map page when run through `Pager`.
#[test]
fn autovacuum_fixture_reads_identically_through_pager() {
    let vfs = UnixVfs;
    let path = Path::new("tests/corpus/fixtures/features/autovacuum.db");
    let header = header_of(&vfs, path);

    let schema_pager = Pager::open(&vfs, path, header.page_size).unwrap();
    let mut schema_cursor = TableCursor::new(schema_pager, &header, 1);
    let schemas = read_schema(&mut schema_cursor, header.text_encoding).unwrap();
    let t = schemas
        .iter()
        .find(|s| s.name == "t")
        .expect("table t in sqlite_master");

    let pager = Pager::open(&vfs, path, header.page_size).unwrap();
    let mut cursor = TableCursor::new(pager, &header, t.root_page);
    let row = cursor.first_row().unwrap().unwrap();
    let values = decode_record(&row.payload, TextEncoding::Utf8).unwrap();
    assert_eq!(text(&values[1]), "auto-vacuum full");
}

fn int(v: &Value) -> i64 {
    match v {
        Value::Integer(i) => *i,
        other => panic!("expected integer, got {other:?}"),
    }
}

/// Opens `name` and returns every row of table `t` as `(a, b)`,
/// discovering `t`'s root page via `read_schema` (never
/// hardcoded) and merging any pending WAL frames through `Pager`.
fn read_table_t(name: &str) -> Vec<(i64, String)> {
    let path = Path::new("tests/corpus/fixtures/journalstates").join(name);
    read_table_t_at(&path)
}

fn read_table_t_at(path: &Path) -> Vec<(i64, String)> {
    let vfs = UnixVfs;
    let header = header_of(&vfs, path);

    let schema_pager = Pager::open(&vfs, path, header.page_size).unwrap();
    let mut schema_cursor = TableCursor::new(schema_pager, &header, 1);
    let schemas = read_schema(&mut schema_cursor, header.text_encoding).unwrap();
    let t = schemas
        .iter()
        .find(|s| s.name == "t")
        .expect("table t in sqlite_master");

    let pager = Pager::open(&vfs, path, header.page_size).unwrap();
    let mut cursor = TableCursor::new(pager, &header, t.root_page);
    let mut rows = Vec::new();
    let mut row = cursor.first_row().unwrap();
    while let Some(r) = row {
        let values = decode_record(&r.payload, header.text_encoding).unwrap();
        rows.push((int(&values[0]), text(&values[1]).to_string()));
        row = cursor.next_row().unwrap();
    }
    rows
}

/// 001-architecture Req-4's "Read a database with uncheckpointed
/// WAL" scenario: three separate commits to the same page, none
/// checkpointed into the main file — all three rows must be
/// visible, matching `sqlite3` (see tools/gen_fixtures.sh).
#[test]
fn wal_pending_fixture_shows_uncheckpointed_rows() {
    assert_eq!(
        read_table_t("wal_pending.db"),
        vec![
            (1, "one".to_string()),
            (2, "two".to_string()),
            (3, "three".to_string()),
        ]
    );
}

/// Both checksum-endianness paths must decode identically — this
/// fixture is `wal_pending.db`'s content with magic flipped to
/// 0x377f0683 and every checksum recomputed in big-endian
/// arithmetic (spike #7 finding 2).
#[test]
fn wal_pending_bigendian_fixture_decodes_identically() {
    assert_eq!(
        read_table_t("wal_pending_bigendian.db"),
        read_table_t("wal_pending.db")
    );
}

/// A committed frame lifted from an unrelated WAL generation
/// (different salts) is appended after this fixture's own last
/// commit — it must never surface, and the WAL's own two
/// legitimate rows must still be visible.
#[test]
fn wal_pending_stale_fixture_rejects_foreign_frame() {
    let rows = read_table_t("wal_pending_stale.db");
    assert_eq!(
        rows,
        vec![(10, "ten".to_string()), (11, "eleven".to_string())]
    );
    assert!(!rows.iter().any(|(_, b)| b.contains("STALE-FRAME")));
}

/// A big transaction spills dirty pages into the WAL as non-commit
/// frames, then rolls back — none of the ~1999 rolled-back rows
/// may surface; only the pre-existing committed row (already
/// flushed to the main file by an earlier checkpoint, before this
/// WAL generation began) is visible.
#[test]
fn wal_pending_trailing_fixture_shows_only_committed_row() {
    assert_eq!(
        read_table_t("wal_pending_trailing.db"),
        vec![(1, "committed-before".to_string())]
    );
}
